services:
  zitadel:
    restart: always
    image: ghcr.io/zitadel/zitadel:v4.13.1
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: postgres
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: 'false'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    networks:
      - zitadel-net

  postgres:
    restart: always
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: zitadel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - '5432:5432'
    networks:
      - zitadel-net

networks:
  zitadel-net:
